/**
 * State-level baby name data — 50 states + DC.
 * Popular names are based on recent SSA state-level data.
 * Cultural influences and naming trends are editorial summaries.
 */

export interface StateData {
  slug: string;
  name: string;
  code: string;
  popularBoys: string[];
  popularGirls: string[];
  namingTrends: string[];
  culturalInfluences: string[];
}

export const states: StateData[] = [
  {
    slug: 'alabama',
    name: 'Alabama',
    code: 'AL',
    popularBoys: ['William', 'James', 'John', 'Elijah', 'Liam', 'Noah', 'Mason', 'Oliver', 'Jaxon', 'Asher'],
    popularGirls: ['Olivia', 'Ava', 'Emma', 'Amelia', 'Harper', 'Evelyn', 'Elizabeth', 'Ella', 'Paisley', 'Addison'],
    namingTrends: ['Biblical names remain dominant', 'Southern double names (Mary Beth, Anna Grace) persist', 'Classic English names with multi-generational appeal'],
    culturalInfluences: ['Deep Southern heritage naming traditions', 'Strong biblical and evangelical influence', 'African-American naming traditions in the Black Belt region'],
  },
  {
    slug: 'alaska',
    name: 'Alaska',
    code: 'AK',
    popularBoys: ['Liam', 'Noah', 'Oliver', 'James', 'Elijah', 'Theodore', 'Henry', 'Jack', 'Wyatt', 'Axel'],
    popularGirls: ['Olivia', 'Emma', 'Aurora', 'Willow', 'Hazel', 'Amelia', 'Isla', 'Charlotte', 'Luna', 'Ivy'],
    namingTrends: ['Nature-inspired names are especially popular', 'Rugged and outdoorsy names resonate', 'Shorter, strong-sounding names preferred'],
    culturalInfluences: ['Alaska Native naming traditions (Inupiat, Yupik, Tlingit)', 'Frontier and wilderness culture', 'Military family influence from large bases'],
  },
  {
    slug: 'arizona',
    name: 'Arizona',
    code: 'AZ',
    popularBoys: ['Liam', 'Noah', 'Mateo', 'Sebastian', 'Oliver', 'Elijah', 'Lucas', 'Ezra', 'Levi', 'James'],
    popularGirls: ['Olivia', 'Emma', 'Mia', 'Camila', 'Sofia', 'Amelia', 'Luna', 'Isabella', 'Ava', 'Charlotte'],
    namingTrends: ['Strong Hispanic naming influence', 'Desert and nature-inspired names gaining ground', 'Bilingual-friendly names that work in English and Spanish'],
    culturalInfluences: ['Large Mexican-American population shaping name trends', 'Native American communities (Navajo, Apache, Tohono O\'odham)', 'Southwestern cultural blend'],
  },
  {
    slug: 'arkansas',
    name: 'Arkansas',
    code: 'AR',
    popularBoys: ['Liam', 'Noah', 'Elijah', 'James', 'Oliver', 'William', 'Hudson', 'Asher', 'Maverick', 'Levi'],
    popularGirls: ['Olivia', 'Emma', 'Ava', 'Amelia', 'Harper', 'Evelyn', 'Paisley', 'Ella', 'Charlotte', 'Hazel'],
    namingTrends: ['Traditional Southern names remain strong', 'Country-style names with rugged appeal', 'Nature and virtue names popular'],
    culturalInfluences: ['Ozark and Southern Appalachian heritage', 'Evangelical Christian naming traditions', 'Rural community naming customs'],
  },
  {
    slug: 'california',
    name: 'California',
    code: 'CA',
    popularBoys: ['Liam', 'Noah', 'Mateo', 'Sebastian', 'Oliver', 'Lucas', 'Ezra', 'Leo', 'Daniel', 'Ethan'],
    popularGirls: ['Olivia', 'Emma', 'Mia', 'Luna', 'Camila', 'Sofia', 'Amelia', 'Isabella', 'Charlotte', 'Gianna'],
    namingTrends: ['Multicultural names reflecting diverse population', 'Celebrity and entertainment industry influence', 'Gender-neutral names rising faster than national average'],
    culturalInfluences: ['Largest Hispanic population in the US drives Latino name trends', 'Asian-American communities (Chinese, Filipino, Vietnamese, Korean)', 'Hollywood and tech culture influence', 'Progressive naming trends as a cultural bellwether'],
  },
  {
    slug: 'colorado',
    name: 'Colorado',
    code: 'CO',
    popularBoys: ['Liam', 'Oliver', 'Noah', 'Theodore', 'Henry', 'Jack', 'James', 'Ezra', 'Leo', 'Asher'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Evelyn', 'Hazel', 'Willow', 'Eleanor', 'Isla', 'Luna'],
    namingTrends: ['Outdoor and nature names very popular', 'Vintage revival names trending strong', 'Short modern names preferred'],
    culturalInfluences: ['Outdoor recreation culture shapes name aesthetics', 'Growing Hispanic community influence', 'Young professional transplant population bringing diverse trends'],
  },
  {
    slug: 'connecticut',
    name: 'Connecticut',
    code: 'CT',
    popularBoys: ['Liam', 'Noah', 'Oliver', 'Theodore', 'Jack', 'Henry', 'James', 'Lucas', 'Benjamin', 'Ethan'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Sophia', 'Mia', 'Isabella', 'Ava', 'Eleanor', 'Ella'],
    namingTrends: ['Classic New England names remain popular', 'Preppy and literary names favored', 'European-influenced naming choices'],
    culturalInfluences: ['New England prep school and Ivy League culture', 'Italian-American and Irish-American naming traditions', 'Suburban affluent naming trends'],
  },
  {
    slug: 'delaware',
    name: 'Delaware',
    code: 'DE',
    popularBoys: ['Liam', 'Noah', 'Oliver', 'James', 'Elijah', 'Theodore', 'Benjamin', 'Henry', 'Lucas', 'Aiden'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Ava', 'Sophia', 'Mia', 'Isabella', 'Harper', 'Ella'],
    namingTrends: ['Mid-Atlantic mix of classic and modern', 'Historical names reflecting colonial heritage', 'Names that bridge Northern and Southern styles'],
    culturalInfluences: ['Mid-Atlantic cultural crossroads', 'African-American naming traditions in Wilmington area', 'DuPont-era old family naming influence'],
  },
  {
    slug: 'district-of-columbia',
    name: 'District of Columbia',
    code: 'DC',
    popularBoys: ['Noah', 'Liam', 'Theodore', 'Oliver', 'Henry', 'Alexander', 'James', 'Benjamin', 'Leo', 'William'],
    popularGirls: ['Charlotte', 'Olivia', 'Eleanor', 'Emma', 'Amelia', 'Sophia', 'Penelope', 'Isla', 'Nora', 'Alice'],
    namingTrends: ['Presidential and historical names especially popular', 'Literary and intellectual names favored', 'Vintage names with strong revival trends'],
    culturalInfluences: ['Political and diplomatic community', 'Highly educated population favoring classic names', 'Diverse international community from embassies and NGOs', 'African-American cultural traditions in historic neighborhoods'],
  },
  {
    slug: 'florida',
    name: 'Florida',
    code: 'FL',
    popularBoys: ['Liam', 'Noah', 'Mateo', 'Lucas', 'Sebastian', 'Oliver', 'Elijah', 'Leo', 'Ezra', 'James'],
    popularGirls: ['Olivia', 'Emma', 'Mia', 'Luna', 'Sofia', 'Camila', 'Isabella', 'Charlotte', 'Amelia', 'Ava'],
    namingTrends: ['Latin American names extremely popular', 'Tropical and nature names emerging', 'Bilingual names that work across cultures'],
    culturalInfluences: ['Cuban, Puerto Rican, and other Caribbean communities', 'Large retiree transplant population', 'Haitian-American naming traditions', 'Brazilian community in South Florida'],
  },
  {
    slug: 'georgia',
    name: 'Georgia',
    code: 'GA',
    popularBoys: ['Liam', 'Noah', 'William', 'James', 'Elijah', 'Oliver', 'Aiden', 'Ethan', 'Mason', 'Asher'],
    popularGirls: ['Olivia', 'Ava', 'Emma', 'Amelia', 'Charlotte', 'Harper', 'Sophia', 'Evelyn', 'Ella', 'Mia'],
    namingTrends: ['Southern gentleman and belle names endure', 'African-American creative naming strong in Atlanta metro', 'Biblical names across demographic groups'],
    culturalInfluences: ['Major African-American cultural hub (Atlanta)', 'Southern heritage naming traditions', 'Growing international community in metro Atlanta'],
  },
  {
    slug: 'hawaii',
    name: 'Hawaii',
    code: 'HI',
    popularBoys: ['Liam', 'Noah', 'Kai', 'Mason', 'Elijah', 'Oliver', 'Ezra', 'Maverick', 'Aiden', 'James'],
    popularGirls: ['Olivia', 'Luna', 'Mia', 'Aria', 'Ava', 'Emma', 'Isla', 'Amelia', 'Leilani', 'Chloe'],
    namingTrends: ['Hawaiian language names widely used across ethnicities', 'Ocean and nature names especially popular', 'Names with vowel-heavy sounds preferred'],
    culturalInfluences: ['Native Hawaiian naming traditions (Kai, Leilani, Koa, Malia)', 'Japanese and Filipino naming influence', 'Pan-Polynesian cultural connections', 'Military family diversity'],
  },
  {
    slug: 'idaho',
    name: 'Idaho',
    code: 'ID',
    popularBoys: ['Oliver', 'Liam', 'Noah', 'Jack', 'Theodore', 'Henry', 'William', 'James', 'Hudson', 'Asher'],
    popularGirls: ['Olivia', 'Emma', 'Charlotte', 'Amelia', 'Hazel', 'Evelyn', 'Ava', 'Willow', 'Harper', 'Ella'],
    namingTrends: ['Western and frontier-inspired names', 'Large families tend toward classic timeless names', 'Nature and virtue names very popular'],
    culturalInfluences: ['LDS (Mormon) naming traditions strong', 'Rural Western heritage', 'Growing Boise metro bringing national trends'],
  },
  {
    slug: 'illinois',
    name: 'Illinois',
    code: 'IL',
    popularBoys: ['Liam', 'Noah', 'Oliver', 'Mateo', 'Theodore', 'Henry', 'Lucas', 'James', 'Ezra', 'Benjamin'],
    popularGirls: ['Olivia', 'Emma', 'Charlotte', 'Amelia', 'Sophia', 'Mia', 'Ava', 'Luna', 'Isabella', 'Evelyn'],
    namingTrends: ['Urban/suburban split between trendy and traditional', 'Eastern European name influence from diaspora communities', 'Hispanic names rising steadily'],
    culturalInfluences: ['Chicago as major immigrant gateway (Polish, Mexican, Irish)', 'African-American naming traditions on the South Side', 'Midwestern traditional values in downstate communities'],
  },
  {
    slug: 'indiana',
    name: 'Indiana',
    code: 'IN',
    popularBoys: ['Liam', 'Oliver', 'Noah', 'Elijah', 'James', 'Theodore', 'Henry', 'Asher', 'Hudson', 'Ezra'],
    popularGirls: ['Olivia', 'Emma', 'Charlotte', 'Amelia', 'Ava', 'Evelyn', 'Harper', 'Hazel', 'Ella', 'Sophia'],
    namingTrends: ['Heartland classic names dominate', 'Country and rustic names popular in rural areas', 'Traditional spelling preferred over creative variations'],
    culturalInfluences: ['Midwestern naming sensibility', 'Motorsport culture (racing names occasionally popular)', 'Amish community traditional naming in northern counties'],
  },
  {
    slug: 'iowa',
    name: 'Iowa',
    code: 'IA',
    popularBoys: ['Oliver', 'Liam', 'Henry', 'Noah', 'Theodore', 'Jack', 'James', 'William', 'Hudson', 'Asher'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Evelyn', 'Harper', 'Ava', 'Ella', 'Hazel', 'Willow'],
    namingTrends: ['Vintage and old-fashioned names trending strong', 'Farm and heritage names persist', 'Scandinavian-influenced names in northern counties'],
    culturalInfluences: ['Scandinavian and German immigrant heritage', 'Rural Midwestern traditional naming', 'College town influence (Iowa City) bringing national trends'],
  },
  {
    slug: 'kansas',
    name: 'Kansas',
    code: 'KS',
    popularBoys: ['Oliver', 'Liam', 'Noah', 'Henry', 'Theodore', 'James', 'William', 'Elijah', 'Hudson', 'Jack'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Evelyn', 'Harper', 'Ava', 'Hazel', 'Ella', 'Eleanor'],
    namingTrends: ['Plains state traditional naming', 'Strong preference for classic biblical names', 'Cowboy and Western names in rural areas'],
    culturalInfluences: ['German-Russian heritage in western Kansas', 'Midwestern farm community values', 'Growing Hispanic population in meatpacking towns'],
  },
  {
    slug: 'kentucky',
    name: 'Kentucky',
    code: 'KY',
    popularBoys: ['Liam', 'Noah', 'James', 'Oliver', 'Elijah', 'William', 'Asher', 'Mason', 'Ezra', 'Hudson'],
    popularGirls: ['Olivia', 'Emma', 'Ava', 'Amelia', 'Harper', 'Charlotte', 'Evelyn', 'Paisley', 'Ella', 'Hazel'],
    namingTrends: ['Appalachian naming traditions with unique spellings', 'Double names (Bobby Joe, Billie Sue) declining but present', 'Country and Southern names popular'],
    culturalInfluences: ['Appalachian mountain heritage naming', 'Bourbon country and horse racing culture', 'Southern Baptist naming traditions'],
  },
  {
    slug: 'louisiana',
    name: 'Louisiana',
    code: 'LA',
    popularBoys: ['Liam', 'Noah', 'John', 'James', 'Elijah', 'Aiden', 'Mason', 'Oliver', 'Asher', 'Jaxon'],
    popularGirls: ['Olivia', 'Ava', 'Emma', 'Amelia', 'Harper', 'Evelyn', 'Charlotte', 'Ella', 'Addison', 'Paisley'],
    namingTrends: ['French-influenced names more common than any other state', 'Saints names popular across cultures', 'Creole and Cajun naming traditions unique to Louisiana'],
    culturalInfluences: ['Cajun and Creole naming heritage (Beau, Pierre, Colette)', 'Strong Catholic saint-naming tradition', 'African-American naming creativity in New Orleans', 'Vietnamese community in the Gulf Coast area'],
  },
  {
    slug: 'maine',
    name: 'Maine',
    code: 'ME',
    popularBoys: ['Liam', 'Oliver', 'Henry', 'Noah', 'Theodore', 'Jack', 'Owen', 'William', 'James', 'Wyatt'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Hazel', 'Willow', 'Eleanor', 'Evelyn', 'Isla', 'Nora'],
    namingTrends: ['New England traditional names strong', 'Nature and maritime names popular', 'Vintage revival names trending'],
    culturalInfluences: ['New England maritime heritage', 'Franco-American naming traditions in the north', 'Rural self-reliance culture influencing strong simple names'],
  },
  {
    slug: 'maryland',
    name: 'Maryland',
    code: 'MD',
    popularBoys: ['Liam', 'Noah', 'Oliver', 'James', 'Elijah', 'Theodore', 'Benjamin', 'Aiden', 'Ethan', 'Henry'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Sophia', 'Ava', 'Mia', 'Isabella', 'Aria', 'Harper'],
    namingTrends: ['Suburban DC influence with educated classic naming', 'African-American naming innovation in Baltimore', 'Mix of Southern and Mid-Atlantic styles'],
    culturalInfluences: ['DC suburbs professional-class naming trends', 'African-American cultural center (Baltimore, Prince George\'s County)', 'Chesapeake maritime heritage'],
  },
  {
    slug: 'massachusetts',
    name: 'Massachusetts',
    code: 'MA',
    popularBoys: ['Liam', 'Noah', 'Oliver', 'Theodore', 'Jack', 'Henry', 'Benjamin', 'James', 'Leo', 'Lucas'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Sophia', 'Eleanor', 'Mia', 'Isla', 'Nora', 'Ava'],
    namingTrends: ['Literary and academic names very popular', 'Irish and Italian heritage names persist', 'Progressive and gender-neutral names trending'],
    culturalInfluences: ['Irish-American and Italian-American deep roots', 'University culture (Harvard, MIT, Boston-area schools)', 'Cape Cod and maritime naming traditions', 'Progressive social values influencing name choices'],
  },
  {
    slug: 'michigan',
    name: 'Michigan',
    code: 'MI',
    popularBoys: ['Liam', 'Noah', 'Oliver', 'Theodore', 'Henry', 'James', 'Elijah', 'Lucas', 'Ezra', 'Asher'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Ava', 'Evelyn', 'Harper', 'Hazel', 'Ella', 'Sophia'],
    namingTrends: ['Midwestern traditional mixed with urban trends', 'Auto industry family names declining', 'Nature names popular in northern Michigan'],
    culturalInfluences: ['Arab-American community in Dearborn (largest outside Middle East)', 'African-American naming traditions in Detroit', 'Dutch heritage in western Michigan', 'Great Lakes outdoor culture'],
  },
  {
    slug: 'minnesota',
    name: 'Minnesota',
    code: 'MN',
    popularBoys: ['Oliver', 'Henry', 'Liam', 'Theodore', 'Noah', 'Jack', 'William', 'James', 'Asher', 'Owen'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Evelyn', 'Amelia', 'Hazel', 'Nora', 'Eleanor', 'Willow', 'Ella'],
    namingTrends: ['Scandinavian names more common than national average', 'Vintage and classic names trend strongly', 'Nature names popular (Lake, River, Forrest)'],
    culturalInfluences: ['Scandinavian and German immigrant heritage', 'Somali-American community in Twin Cities', 'Hmong community naming traditions', 'Lake country outdoor culture'],
  },
  {
    slug: 'mississippi',
    name: 'Mississippi',
    code: 'MS',
    popularBoys: ['James', 'John', 'William', 'Liam', 'Noah', 'Elijah', 'Mason', 'Aiden', 'Asher', 'Jaxon'],
    popularGirls: ['Olivia', 'Ava', 'Emma', 'Amelia', 'Harper', 'Paisley', 'Evelyn', 'Addison', 'Ella', 'Elizabeth'],
    namingTrends: ['Traditional biblical names dominate more than any other state', 'Double first names (Mary Grace, John David) still common', 'Heritage family names passed down through generations'],
    culturalInfluences: ['Deep South naming traditions', 'Strong African-American naming heritage', 'Evangelical Christian influence on name choices', 'Delta blues cultural heritage'],
  },
  {
    slug: 'missouri',
    name: 'Missouri',
    code: 'MO',
    popularBoys: ['Liam', 'Oliver', 'Noah', 'Henry', 'Elijah', 'James', 'Theodore', 'William', 'Asher', 'Hudson'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Ava', 'Evelyn', 'Harper', 'Hazel', 'Ella', 'Eleanor'],
    namingTrends: ['Blend of Midwestern and Southern naming styles', 'Classic names preferred in rural areas', 'Urban centers follow national trends closely'],
    culturalInfluences: ['Gateway West cultural heritage', 'German heritage in St. Louis and Missouri River towns', 'Ozark mountain community traditions', 'Kansas City jazz and cultural traditions'],
  },
  {
    slug: 'montana',
    name: 'Montana',
    code: 'MT',
    popularBoys: ['Oliver', 'Liam', 'Jack', 'Noah', 'Henry', 'Theodore', 'James', 'Wyatt', 'William', 'Hudson'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Hazel', 'Amelia', 'Willow', 'Evelyn', 'Harper', 'Eleanor', 'Ella'],
    namingTrends: ['Western frontier names very popular', 'Nature and outdoors names dominant', 'Strong classic names preferred over trendy'],
    culturalInfluences: ['Big Sky Country ranching culture', 'Native American communities (Blackfeet, Crow, Salish)', 'Scandinavian homesteader heritage in eastern Montana'],
  },
  {
    slug: 'nebraska',
    name: 'Nebraska',
    code: 'NE',
    popularBoys: ['Oliver', 'Liam', 'Henry', 'Noah', 'Theodore', 'William', 'Jack', 'James', 'Hudson', 'Asher'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Evelyn', 'Harper', 'Ava', 'Hazel', 'Ella', 'Eleanor'],
    namingTrends: ['Heartland traditional naming strong', 'German and Czech heritage names persist', 'Farm and prairie names in rural communities'],
    culturalInfluences: ['German and Czech immigrant heritage', 'Growing Hispanic and Sudanese refugee communities in Omaha', 'University of Nebraska community influence'],
  },
  {
    slug: 'nevada',
    name: 'Nevada',
    code: 'NV',
    popularBoys: ['Liam', 'Noah', 'Mateo', 'Sebastian', 'Oliver', 'Lucas', 'Elijah', 'Ezra', 'Leo', 'James'],
    popularGirls: ['Olivia', 'Emma', 'Mia', 'Luna', 'Sofia', 'Camila', 'Isabella', 'Charlotte', 'Amelia', 'Ava'],
    namingTrends: ['Hispanic naming influence very strong', 'Entertainment and celebrity names popular', 'Western frontier names in rural areas'],
    culturalInfluences: ['Large Hispanic population (nearly 30%)', 'Las Vegas entertainment culture', 'Filipino-American community', 'Mining and ranching heritage in rural Nevada'],
  },
  {
    slug: 'new-hampshire',
    name: 'New Hampshire',
    code: 'NH',
    popularBoys: ['Liam', 'Oliver', 'Henry', 'Noah', 'Theodore', 'Jack', 'Owen', 'James', 'Benjamin', 'William'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Hazel', 'Eleanor', 'Evelyn', 'Nora', 'Willow', 'Isla'],
    namingTrends: ['New England traditional names dominant', 'Nature and woodland names popular', 'Strong vintage revival trend'],
    culturalInfluences: ['Yankee New England heritage', 'French-Canadian influence in northern towns', 'Live Free or Die independent spirit reflected in unique choices'],
  },
  {
    slug: 'new-jersey',
    name: 'New Jersey',
    code: 'NJ',
    popularBoys: ['Liam', 'Noah', 'Oliver', 'Mateo', 'Lucas', 'Theodore', 'James', 'Benjamin', 'Ethan', 'Henry'],
    popularGirls: ['Olivia', 'Emma', 'Charlotte', 'Sophia', 'Mia', 'Amelia', 'Isabella', 'Ava', 'Luna', 'Aria'],
    namingTrends: ['Extremely diverse naming reflecting the state population', 'Italian and South Asian names common', 'Suburban family classic names trending'],
    culturalInfluences: ['Italian-American naming traditions (one of the strongest in the US)', 'Indian and Pakistani communities with Sanskrit and Urdu names', 'Large Jewish community with Hebrew naming traditions', 'NYC metro cultural spillover'],
  },
  {
    slug: 'new-mexico',
    name: 'New Mexico',
    code: 'NM',
    popularBoys: ['Liam', 'Noah', 'Mateo', 'Sebastian', 'Elijah', 'Oliver', 'Ezra', 'Lucas', 'Gabriel', 'Isaiah'],
    popularGirls: ['Olivia', 'Mia', 'Luna', 'Sofia', 'Emma', 'Camila', 'Amelia', 'Isabella', 'Aria', 'Ava'],
    namingTrends: ['Spanish and Native American names deeply embedded', 'Saint names from Catholic tradition common', 'Bilingual names standard'],
    culturalInfluences: ['Hispano naming traditions dating back centuries', 'Pueblo, Navajo, and Apache naming practices', 'Catholic patron saint naming tradition', 'Land of Enchantment artistic community'],
  },
  {
    slug: 'new-york',
    name: 'New York',
    code: 'NY',
    popularBoys: ['Liam', 'Noah', 'Mateo', 'Lucas', 'Oliver', 'Theodore', 'Ethan', 'Benjamin', 'Henry', 'James'],
    popularGirls: ['Olivia', 'Emma', 'Charlotte', 'Sophia', 'Mia', 'Amelia', 'Ava', 'Luna', 'Isabella', 'Aria'],
    namingTrends: ['Extremely diverse naming reflecting global immigration', 'Intellectual and cultural names popular in NYC', 'Upstate trends more traditional and New England influenced'],
    culturalInfluences: ['Global immigration gateway — naming from every culture', 'Jewish naming traditions (Hebrew and Yiddish)', 'Caribbean and Latin American influence in NYC', 'Italian-American heritage', 'African-American cultural innovation'],
  },
  {
    slug: 'north-carolina',
    name: 'North Carolina',
    code: 'NC',
    popularBoys: ['Liam', 'Noah', 'Oliver', 'William', 'James', 'Elijah', 'Theodore', 'Henry', 'Asher', 'Mason'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Ava', 'Harper', 'Evelyn', 'Sophia', 'Ella', 'Mia'],
    namingTrends: ['Charlotte (the city name) consistently ranks high for girls', 'Southern classic names blending with Research Triangle modern tastes', 'Nature and mountain names emerging'],
    culturalInfluences: ['Southern heritage naming traditions', 'Growing tech corridor attracting diverse transplants', 'Cherokee naming traditions in western NC', 'African-American naming traditions in Piedmont'],
  },
  {
    slug: 'north-dakota',
    name: 'North Dakota',
    code: 'ND',
    popularBoys: ['Oliver', 'Henry', 'Liam', 'Jack', 'Theodore', 'Noah', 'William', 'James', 'Hudson', 'Asher'],
    popularGirls: ['Olivia', 'Charlotte', 'Harper', 'Emma', 'Amelia', 'Evelyn', 'Hazel', 'Willow', 'Ella', 'Eleanor'],
    namingTrends: ['Scandinavian and German heritage names persist', 'Classic heartland names dominate', 'Oil boom bringing diverse naming to western ND'],
    culturalInfluences: ['Norwegian and German-Russian immigrant heritage', 'Native American communities (Mandan, Hidatsa, Arikara)', 'Small-town traditional naming values', 'Bakken oil field worker diversity'],
  },
  {
    slug: 'ohio',
    name: 'Ohio',
    code: 'OH',
    popularBoys: ['Liam', 'Noah', 'Oliver', 'Elijah', 'James', 'Theodore', 'Henry', 'Asher', 'Hudson', 'Ezra'],
    popularGirls: ['Olivia', 'Emma', 'Charlotte', 'Amelia', 'Ava', 'Evelyn', 'Harper', 'Hazel', 'Sophia', 'Ella'],
    namingTrends: ['Midwest traditional meets Rust Belt practicality', 'Amish traditional naming in Holmes County area', 'Classic names strong across the state'],
    culturalInfluences: ['German-American heritage (Cincinnati, Columbus)', 'Amish and Mennonite naming traditions', 'African-American naming traditions in Cleveland and Columbus', 'Appalachian naming influence in southeastern Ohio'],
  },
  {
    slug: 'oklahoma',
    name: 'Oklahoma',
    code: 'OK',
    popularBoys: ['Liam', 'Noah', 'Oliver', 'Elijah', 'James', 'Asher', 'Maverick', 'Hudson', 'Ezra', 'Levi'],
    popularGirls: ['Olivia', 'Emma', 'Ava', 'Amelia', 'Charlotte', 'Harper', 'Evelyn', 'Paisley', 'Ella', 'Hazel'],
    namingTrends: ['Western and cowboy names still popular', 'Native American naming influence notable', 'Southern and plains naming blend'],
    culturalInfluences: ['Largest Native American population by percentage (Cherokee, Choctaw, Chickasaw)', 'Oklahoma land rush pioneer heritage', 'Bible Belt naming traditions', 'Growing Hispanic community'],
  },
  {
    slug: 'oregon',
    name: 'Oregon',
    code: 'OR',
    popularBoys: ['Oliver', 'Liam', 'Noah', 'Theodore', 'Henry', 'Jack', 'Jasper', 'Ezra', 'Leo', 'Felix'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Hazel', 'Willow', 'Amelia', 'Luna', 'Isla', 'Eleanor', 'Ivy'],
    namingTrends: ['Nature and botanical names extremely popular', 'Quirky and unique names embraced', 'Gender-neutral names higher than national average'],
    culturalInfluences: ['Pacific Northwest environmental culture', 'Progressive Portland naming trends set state patterns', 'Oregon Trail pioneer heritage', 'Growing Hispanic community in agricultural regions'],
  },
  {
    slug: 'pennsylvania',
    name: 'Pennsylvania',
    code: 'PA',
    popularBoys: ['Liam', 'Noah', 'Oliver', 'Theodore', 'Henry', 'James', 'Benjamin', 'Elijah', 'Lucas', 'Ezra'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Sophia', 'Ava', 'Mia', 'Evelyn', 'Harper', 'Ella'],
    namingTrends: ['Philadelphia urban trends contrast with rural Pennsylvania Dutch country', 'Historical and founding-era names popular', 'Italian and Irish heritage names persist'],
    culturalInfluences: ['Pennsylvania Dutch (Amish/Mennonite) naming traditions', 'Philadelphia Italian-American and Irish-American communities', 'Pittsburgh Eastern European heritage (Polish, Slovak, Ukrainian)', 'Historical Quaker naming simplicity'],
  },
  {
    slug: 'rhode-island',
    name: 'Rhode Island',
    code: 'RI',
    popularBoys: ['Liam', 'Noah', 'Oliver', 'Theodore', 'Lucas', 'Jack', 'Henry', 'James', 'Benjamin', 'Leo'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Sophia', 'Mia', 'Isabella', 'Ava', 'Aria', 'Luna'],
    namingTrends: ['Portuguese and Italian heritage names strong', 'New England classic names popular', 'Small state follows national trends closely'],
    culturalInfluences: ['Portuguese-American community (largest concentration in US)', 'Italian-American naming traditions', 'Cape Verdean community', 'Providence as a college town influencing trends'],
  },
  {
    slug: 'south-carolina',
    name: 'South Carolina',
    code: 'SC',
    popularBoys: ['William', 'Liam', 'Noah', 'James', 'Elijah', 'Oliver', 'Mason', 'Asher', 'Aiden', 'Jaxon'],
    popularGirls: ['Olivia', 'Ava', 'Emma', 'Amelia', 'Charlotte', 'Harper', 'Evelyn', 'Ella', 'Paisley', 'Sophia'],
    namingTrends: ['Southern charm names extremely popular', 'Charleston old-money classic names trending nationally', 'Biblical names remain top choices'],
    culturalInfluences: ['Lowcountry and Gullah naming heritage', 'Southern plantation-era naming traditions', 'Military naming (large base presence)', 'African-American naming creativity'],
  },
  {
    slug: 'south-dakota',
    name: 'South Dakota',
    code: 'SD',
    popularBoys: ['Oliver', 'Liam', 'Henry', 'Noah', 'Jack', 'Theodore', 'William', 'Hudson', 'James', 'Asher'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Harper', 'Amelia', 'Evelyn', 'Hazel', 'Ella', 'Willow', 'Eleanor'],
    namingTrends: ['Plains heartland classic names', 'Native American names used in reservation communities', 'Ranching and frontier names popular'],
    culturalInfluences: ['Lakota Sioux naming traditions', 'Scandinavian and German heritage', 'Small-town prairie community values', 'Hutterite colony traditional naming'],
  },
  {
    slug: 'tennessee',
    name: 'Tennessee',
    code: 'TN',
    popularBoys: ['Liam', 'Noah', 'Oliver', 'James', 'William', 'Elijah', 'Asher', 'Mason', 'Hudson', 'Ezra'],
    popularGirls: ['Olivia', 'Emma', 'Ava', 'Amelia', 'Charlotte', 'Harper', 'Evelyn', 'Ella', 'Paisley', 'Hazel'],
    namingTrends: ['Country music influence on naming (Nashville effect)', 'Southern classic names dominant', 'Musical and artistic names emerging'],
    culturalInfluences: ['Nashville music industry and celebrity naming trends', 'Memphis blues and soul cultural heritage', 'Appalachian mountain naming in eastern Tennessee', 'Southern evangelical naming traditions'],
  },
  {
    slug: 'texas',
    name: 'Texas',
    code: 'TX',
    popularBoys: ['Liam', 'Noah', 'Mateo', 'Sebastian', 'Oliver', 'Lucas', 'Elijah', 'Ezra', 'James', 'Leo'],
    popularGirls: ['Olivia', 'Emma', 'Mia', 'Camila', 'Sofia', 'Luna', 'Charlotte', 'Amelia', 'Isabella', 'Ava'],
    namingTrends: ['Hispanic names are mainstream, not minority trend', 'Big bold names matching Texas personality', 'Cowboy and Western heritage names persist in rural areas'],
    culturalInfluences: ['Largest Hispanic population in raw numbers', 'Tejano cultural naming traditions', 'German Hill Country heritage', 'Vietnamese community in Houston', 'African-American naming traditions in East Texas and Dallas'],
  },
  {
    slug: 'utah',
    name: 'Utah',
    code: 'UT',
    popularBoys: ['Oliver', 'Liam', 'Theodore', 'Henry', 'Jack', 'Noah', 'James', 'William', 'Asher', 'Ezra'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Hazel', 'Amelia', 'Evelyn', 'Ivy', 'Willow', 'Lucy', 'June'],
    namingTrends: ['Utah leads the nation in unique name creation', 'Large families explore deeper into name lists', 'Creative spelling variations more common than any other state'],
    culturalInfluences: ['LDS (Mormon) culture of large families drives unique naming', 'Pioneer heritage names honored', 'Young marriage age means younger parents choosing trendier names', 'Western outdoor culture'],
  },
  {
    slug: 'vermont',
    name: 'Vermont',
    code: 'VT',
    popularBoys: ['Oliver', 'Henry', 'Liam', 'Theodore', 'Noah', 'Jack', 'Owen', 'William', 'James', 'Jasper'],
    popularGirls: ['Olivia', 'Charlotte', 'Hazel', 'Amelia', 'Emma', 'Willow', 'Eleanor', 'Isla', 'Nora', 'Violet'],
    namingTrends: ['Nature and botanical names extremely popular', 'Vintage New England names trending strong', 'Artisanal and literary names embraced'],
    culturalInfluences: ['Green Mountain agrarian culture', 'Progressive and artistic community', 'Franco-American heritage in northern Vermont', 'Back-to-the-land movement culture'],
  },
  {
    slug: 'virginia',
    name: 'Virginia',
    code: 'VA',
    popularBoys: ['Liam', 'Noah', 'Oliver', 'James', 'William', 'Theodore', 'Henry', 'Benjamin', 'Elijah', 'Ethan'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Sophia', 'Ava', 'Eleanor', 'Evelyn', 'Harper', 'Ella'],
    namingTrends: ['Presidential and founding-father names more popular here than nationally', 'Northern Virginia follows DC/suburban trends', 'Southern Virginia maintains traditional naming'],
    culturalInfluences: ['Colonial and founding-era heritage (naming after presidents)', 'DC suburbs professional-class naming', 'Military family diversity (Norfolk, Hampton Roads)', 'Growing Asian-American community in Northern Virginia'],
  },
  {
    slug: 'washington',
    name: 'Washington',
    code: 'WA',
    popularBoys: ['Oliver', 'Liam', 'Noah', 'Theodore', 'Henry', 'Jack', 'Leo', 'Ezra', 'James', 'Jasper'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Luna', 'Hazel', 'Willow', 'Isla', 'Eleanor', 'Evelyn'],
    namingTrends: ['Pacific Northwest nature names trending', 'Tech industry creative naming in Seattle metro', 'Asian-influenced names from growing communities'],
    culturalInfluences: ['Seattle tech industry culture', 'Pacific Northwest outdoor and environmental culture', 'Asian-American communities (Chinese, Vietnamese, Filipino)', 'Scandinavian heritage in rural areas'],
  },
  {
    slug: 'west-virginia',
    name: 'West Virginia',
    code: 'WV',
    popularBoys: ['Liam', 'Noah', 'James', 'Oliver', 'Elijah', 'Mason', 'Asher', 'Hudson', 'Ezra', 'Wyatt'],
    popularGirls: ['Olivia', 'Emma', 'Ava', 'Amelia', 'Harper', 'Charlotte', 'Paisley', 'Evelyn', 'Hazel', 'Ella'],
    namingTrends: ['Appalachian heritage names strong', 'Country and mountain names popular', 'Traditional spelling preferred'],
    culturalInfluences: ['Appalachian mountain community naming traditions', 'Coal country heritage names', 'Scotch-Irish naming influence', 'Strong family-name-passing traditions'],
  },
  {
    slug: 'wisconsin',
    name: 'Wisconsin',
    code: 'WI',
    popularBoys: ['Oliver', 'Liam', 'Henry', 'Noah', 'Theodore', 'Jack', 'William', 'James', 'Owen', 'Asher'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Amelia', 'Evelyn', 'Harper', 'Hazel', 'Nora', 'Eleanor', 'Ella'],
    namingTrends: ['German and Scandinavian heritage names persist', 'Midwest traditional naming strong', 'Cheese state culture has not produced cheese-themed names yet'],
    culturalInfluences: ['German-American heritage (strongest in the US)', 'Scandinavian community in northern Wisconsin', 'Hmong community naming traditions in Milwaukee and Wausau', 'Dairy farm community traditional naming'],
  },
  {
    slug: 'wyoming',
    name: 'Wyoming',
    code: 'WY',
    popularBoys: ['Oliver', 'Liam', 'Jack', 'Noah', 'Henry', 'James', 'Wyatt', 'William', 'Theodore', 'Hudson'],
    popularGirls: ['Olivia', 'Charlotte', 'Emma', 'Hazel', 'Amelia', 'Harper', 'Willow', 'Evelyn', 'Ella', 'Eleanor'],
    namingTrends: ['Western frontier names most popular in the country', 'Nature and mountain names dominant', 'Strong classic names preferred'],
    culturalInfluences: ['Cowboy and ranching culture', 'Yellowstone and Grand Teton outdoor heritage', 'Native American communities (Eastern Shoshone, Northern Arapaho)', 'Smallest population means individual choices have outsized effect on rankings'],
  },
];

export function getAllStates(): StateData[] {
  return states;
}

export function getStateBySlug(slug: string): StateData | undefined {
  return states.find((s) => s.slug === slug);
}
