"""
Enrich baby names database with meanings and origins for top names.
Uses a curated dataset of name meanings.
"""
import os
import sqlite3

DATA_DIR = os.path.join(os.path.dirname(__file__), '..', 'data')
DB_PATH = os.path.join(DATA_DIR, 'names.db')

# Comprehensive name meanings for top 500+ names
# Format: (name_lowercase, origin, meaning)
NAME_DATA = [
    # Top Boy Names
    ("james", "Hebrew", "Supplanter"),
    ("robert", "Germanic", "Bright fame"),
    ("john", "Hebrew", "God is gracious"),
    ("michael", "Hebrew", "Who is like God?"),
    ("david", "Hebrew", "Beloved"),
    ("william", "Germanic", "Resolute protector"),
    ("richard", "Germanic", "Brave ruler"),
    ("joseph", "Hebrew", "He will add"),
    ("thomas", "Aramaic", "Twin"),
    ("charles", "Germanic", "Free man"),
    ("christopher", "Greek", "Bearer of Christ"),
    ("daniel", "Hebrew", "God is my judge"),
    ("matthew", "Hebrew", "Gift of God"),
    ("anthony", "Latin", "Priceless one"),
    ("mark", "Latin", "Warlike, dedicated to Mars"),
    ("donald", "Gaelic", "World ruler"),
    ("steven", "Greek", "Crown, wreath"),
    ("paul", "Latin", "Small, humble"),
    ("andrew", "Greek", "Manly, brave"),
    ("joshua", "Hebrew", "God is salvation"),
    ("kenneth", "Gaelic", "Handsome, born of fire"),
    ("kevin", "Irish", "Gentle, handsome birth"),
    ("brian", "Irish", "Noble, strong, virtuous"),
    ("george", "Greek", "Farmer, earth worker"),
    ("timothy", "Greek", "Honoring God"),
    ("ronald", "Norse", "Ruler's counselor"),
    ("edward", "English", "Wealthy guardian"),
    ("jason", "Greek", "Healer"),
    ("jeffrey", "Germanic", "Peaceful pledge"),
    ("ryan", "Irish", "Little king"),
    ("jacob", "Hebrew", "Supplanter, held by the heel"),
    ("gary", "Germanic", "Spear"),
    ("nicholas", "Greek", "Victory of the people"),
    ("eric", "Norse", "Eternal ruler"),
    ("jonathan", "Hebrew", "God has given"),
    ("stephen", "Greek", "Crown, wreath"),
    ("larry", "Latin", "Laurel-crowned"),
    ("justin", "Latin", "Just, righteous"),
    ("scott", "English", "From Scotland"),
    ("brandon", "English", "Broom-covered hill"),
    ("benjamin", "Hebrew", "Son of the right hand"),
    ("samuel", "Hebrew", "Heard by God"),
    ("raymond", "Germanic", "Wise protector"),
    ("gregory", "Greek", "Watchful, alert"),
    ("frank", "Germanic", "Free man"),
    ("alexander", "Greek", "Defender of the people"),
    ("patrick", "Latin", "Nobleman, patrician"),
    ("jack", "English", "God is gracious"),
    ("dennis", "Greek", "Follower of Dionysus"),
    ("jerry", "Germanic", "Spear ruler"),
    ("tyler", "English", "Tile maker"),
    ("aaron", "Hebrew", "Exalted, enlightened"),
    ("jose", "Spanish", "God will increase"),
    ("adam", "Hebrew", "Man, earth"),
    ("nathan", "Hebrew", "He gave"),
    ("henry", "Germanic", "Ruler of the home"),
    ("peter", "Greek", "Rock, stone"),
    ("zachary", "Hebrew", "God remembers"),
    ("douglas", "Gaelic", "Dark river"),
    ("harold", "Norse", "Army ruler"),
    ("liam", "Irish", "Strong-willed warrior"),
    ("noah", "Hebrew", "Rest, comfort"),
    ("oliver", "Latin", "Olive tree"),
    ("elijah", "Hebrew", "My God is Yahweh"),
    ("lucas", "Greek", "Light, illumination"),
    ("mason", "English", "Stone worker"),
    ("logan", "Gaelic", "Little hollow"),
    ("ethan", "Hebrew", "Strong, firm, enduring"),
    ("aiden", "Irish", "Little fire"),
    ("jackson", "English", "Son of Jack"),
    ("sebastian", "Greek", "Venerable, revered"),
    ("mateo", "Spanish", "Gift of God"),
    ("owen", "Welsh", "Young warrior, noble"),
    ("theodore", "Greek", "Gift of God"),
    ("leo", "Latin", "Lion"),
    ("hudson", "English", "Son of Hugh"),
    ("asher", "Hebrew", "Happy, blessed"),
    ("ezra", "Hebrew", "Helper, aid"),
    ("miles", "Latin", "Soldier, merciful"),
    ("lincoln", "English", "Lake colony"),
    ("caleb", "Hebrew", "Faithful, bold"),
    ("dylan", "Welsh", "Son of the sea"),
    ("luke", "Greek", "Light-giving"),
    ("gabriel", "Hebrew", "God is my strength"),
    ("isaac", "Hebrew", "He will laugh"),
    ("carter", "English", "Cart driver"),
    ("connor", "Irish", "Lover of wolves"),
    ("julian", "Latin", "Youthful, downy"),
    ("wyatt", "English", "Brave in war"),
    ("jaxon", "English", "Son of Jack"),
    ("landon", "English", "Long hill"),
    ("grayson", "English", "Son of the gray-haired one"),
    ("isaiah", "Hebrew", "Salvation of the Lord"),
    ("hunter", "English", "One who hunts"),
    ("nolan", "Irish", "Noble, famous"),
    ("jordan", "Hebrew", "To flow down"),
    ("christian", "Latin", "Follower of Christ"),
    ("cameron", "Gaelic", "Crooked nose"),
    ("colton", "English", "From the coal town"),
    ("adrian", "Latin", "From Hadria"),
    ("eli", "Hebrew", "Ascended, uplifted"),
    ("kai", "Hawaiian", "Sea"),
    ("max", "Latin", "Greatest"),
    ("ian", "Scottish", "God is gracious"),
    ("dominic", "Latin", "Belonging to the Lord"),
    ("austin", "Latin", "Great, magnificent"),
    ("everett", "English", "Brave as a wild boar"),
    ("brooks", "English", "Near the brook"),
    ("xavier", "Arabic", "Bright, splendid"),
    ("kai", "Hawaiian", "Sea, ocean"),
    ("jose", "Spanish", "God will increase"),
    ("angel", "Greek", "Messenger of God"),
    ("cooper", "English", "Barrel maker"),
    ("parker", "English", "Park keeper"),
    ("roman", "Latin", "Citizen of Rome"),
    ("easton", "English", "East-facing place"),
    ("axel", "Scandinavian", "Father of peace"),
    ("jameson", "English", "Son of James"),
    ("carson", "Scottish", "Son of the marsh dwellers"),
    ("jace", "Greek", "Healer"),
    ("maverick", "American", "Independent, nonconformist"),
    ("beckett", "English", "Bee cottage"),
    ("emiliano", "Latin", "Rival, eager"),
    ("jasper", "Persian", "Bringer of treasure"),
    ("atlas", "Greek", "Bearer of the heavens"),
    ("felix", "Latin", "Happy, fortunate"),
    ("silas", "Latin", "Forest, woods"),
    ("august", "Latin", "Great, venerable"),
    ("archer", "English", "Bowman"),
    ("rowan", "Gaelic", "Little red one"),
    ("sawyer", "English", "Wood cutter"),
    ("weston", "English", "From the western town"),
    ("ryder", "English", "Horseman, rider"),
    # Top Girl Names
    ("mary", "Hebrew", "Beloved, wished-for child"),
    ("patricia", "Latin", "Noble woman"),
    ("jennifer", "Welsh", "White wave, fair one"),
    ("linda", "Germanic", "Soft, tender, beautiful"),
    ("barbara", "Greek", "Foreign, strange"),
    ("elizabeth", "Hebrew", "God is my oath"),
    ("susan", "Hebrew", "Lily, graceful"),
    ("jessica", "Hebrew", "God beholds"),
    ("sarah", "Hebrew", "Princess, noblewoman"),
    ("karen", "Danish", "Pure"),
    ("lisa", "Hebrew", "God's promise"),
    ("nancy", "Hebrew", "Grace, favor"),
    ("betty", "Hebrew", "God's promise"),
    ("dorothy", "Greek", "Gift of God"),
    ("sandra", "Greek", "Defender of mankind"),
    ("ashley", "English", "Ash tree meadow"),
    ("kimberly", "English", "Royal fortress meadow"),
    ("emily", "Latin", "Rival, industrious"),
    ("donna", "Italian", "Lady"),
    ("michelle", "Hebrew", "Who is like God?"),
    ("carol", "Germanic", "Free woman, joyful song"),
    ("amanda", "Latin", "Lovable, worthy of love"),
    ("melissa", "Greek", "Honey bee"),
    ("deborah", "Hebrew", "Bee, industrious"),
    ("stephanie", "Greek", "Crown, wreath, garland"),
    ("rebecca", "Hebrew", "To tie, to bind, captivating"),
    ("sharon", "Hebrew", "A flat plain, princess"),
    ("laura", "Latin", "Laurel, bay tree"),
    ("cynthia", "Greek", "Moon goddess"),
    ("kathleen", "Irish", "Pure, clear"),
    ("amy", "French", "Beloved"),
    ("angela", "Greek", "Angel, messenger of God"),
    ("shirley", "English", "Bright meadow"),
    ("anna", "Hebrew", "Grace, favor"),
    ("brenda", "Norse", "Sword, torch"),
    ("pamela", "Greek", "All sweetness, honey"),
    ("emma", "Germanic", "Whole, universal"),
    ("nicole", "Greek", "Victory of the people"),
    ("helen", "Greek", "Bright, shining light"),
    ("samantha", "Aramaic", "Listener, heard by God"),
    ("katherine", "Greek", "Pure, clear"),
    ("christine", "Latin", "Follower of Christ"),
    ("rachel", "Hebrew", "Ewe, gentle, innocent"),
    ("maria", "Hebrew", "Beloved, sea of bitterness"),
    ("heather", "English", "Flowering heath plant"),
    ("diane", "Latin", "Divine, heavenly"),
    ("ruth", "Hebrew", "Friend, companion"),
    ("julie", "Latin", "Youthful, soft-haired"),
    ("olivia", "Latin", "Olive tree, peace"),
    ("victoria", "Latin", "Victory, conqueror"),
    ("kelly", "Irish", "Warrior, bright-headed"),
    ("lauren", "Latin", "Laurel, crowned with laurel"),
    ("christina", "Latin", "Follower of Christ"),
    ("joan", "Hebrew", "God is gracious"),
    ("evelyn", "English", "Wished-for child, life"),
    ("judith", "Hebrew", "Woman from Judea, praised"),
    ("megan", "Welsh", "Pearl, strong and capable"),
    ("andrea", "Greek", "Brave, strong, manly"),
    ("cheryl", "French", "Beloved, dear one"),
    ("hannah", "Hebrew", "Grace, favor"),
    ("jacqueline", "French", "Supplanter"),
    ("martha", "Aramaic", "Lady, mistress of the house"),
    ("gloria", "Latin", "Glory, fame"),
    ("teresa", "Greek", "Harvester, reaper"),
    ("sara", "Hebrew", "Princess"),
    ("madison", "English", "Son of Maud, strong fighter"),
    ("abigail", "Hebrew", "Father's joy, source of joy"),
    ("alice", "Germanic", "Noble, exalted"),
    ("sophia", "Greek", "Wisdom"),
    ("grace", "Latin", "Grace, blessing, elegance"),
    ("amber", "Arabic", "Jewel, precious stone"),
    ("natalie", "Latin", "Born on Christmas day"),
    ("brittany", "French", "From Brittany, Britain"),
    ("charlotte", "French", "Free woman, petite"),
    ("marie", "Hebrew", "Beloved, sea of bitterness"),
    ("kayla", "Hebrew", "Crown of laurels"),
    ("alexis", "Greek", "Defender, helper"),
    ("isabella", "Hebrew", "Devoted to God"),
    ("ava", "Latin", "Life, bird-like"),
    ("mia", "Scandinavian", "Mine, beloved"),
    ("amelia", "Germanic", "Industrious, striving"),
    ("harper", "English", "Harp player"),
    ("scarlett", "English", "Red, bright"),
    ("penelope", "Greek", "Weaver, faithful wife"),
    ("layla", "Arabic", "Night, dark beauty"),
    ("chloe", "Greek", "Blooming, young green shoot"),
    ("riley", "Irish", "Courageous, valiant"),
    ("zoey", "Greek", "Life, alive"),
    ("nora", "Irish", "Honor, light"),
    ("lily", "English", "Lily flower, purity"),
    ("eleanor", "Greek", "Bright, shining one"),
    ("hazel", "English", "Hazel tree, wisdom"),
    ("violet", "Latin", "Purple flower"),
    ("aurora", "Latin", "Dawn, new beginning"),
    ("savannah", "Spanish", "Treeless plain"),
    ("audrey", "English", "Noble strength"),
    ("brooklyn", "English", "Water, stream"),
    ("bella", "Italian", "Beautiful"),
    ("claire", "Latin", "Clear, bright, famous"),
    ("skylar", "Dutch", "Scholar, sheltering"),
    ("lucy", "Latin", "Light"),
    ("paisley", "Scottish", "Church, place of worship"),
    ("stella", "Latin", "Star"),
    ("natalia", "Latin", "Born on Christmas"),
    ("ivy", "English", "Ivy plant, faithfulness"),
    ("leah", "Hebrew", "Weary, meadow"),
    ("elena", "Greek", "Bright, shining light"),
    ("vivian", "Latin", "Alive, full of life"),
    ("maya", "Sanskrit", "Illusion, dream"),
    ("naomi", "Hebrew", "Pleasantness, delight"),
    ("ruby", "Latin", "Red gemstone, precious"),
    ("luna", "Latin", "Moon"),
    ("camila", "Latin", "Young ceremonial attendant"),
    ("aria", "Italian", "Air, melody, song"),
    ("willow", "English", "Willow tree, graceful"),
    ("emilia", "Latin", "Rival, industrious"),
    ("valentina", "Latin", "Strong, healthy"),
    ("gianna", "Italian", "God is gracious"),
    ("kennedy", "Irish", "Helmeted chief"),
    ("kinsley", "English", "King's meadow"),
    ("delilah", "Hebrew", "Delicate, languishing"),
    ("serenity", "Latin", "Peaceful, serene"),
    ("piper", "English", "Pipe player"),
    ("quinn", "Irish", "Wise, counsel"),
    ("adalynn", "Germanic", "Noble one"),
    ("athena", "Greek", "Goddess of wisdom"),
    ("sadie", "Hebrew", "Princess"),
    ("autumn", "Latin", "Fall season"),
    ("genesis", "Greek", "Origin, beginning"),
    ("eva", "Hebrew", "Life, living one"),
    ("ariana", "Italian", "Most holy"),
    ("madeline", "French", "Woman from Magdala"),
    ("adalyn", "Germanic", "Noble"),
    ("alice", "Germanic", "Noble, of the nobility"),
    ("nova", "Latin", "New, star"),
    ("isla", "Scottish", "Island"),
    ("cora", "Greek", "Maiden"),
    ("elise", "French", "God's promise"),
    ("lydia", "Greek", "Noble one, from Lydia"),
    ("lila", "Arabic", "Night, dark beauty"),
    ("margot", "French", "Pearl"),
    ("adaline", "Germanic", "Noble"),
    ("josie", "Hebrew", "God will increase"),
    ("sage", "Latin", "Wise, knowing"),
    ("freya", "Norse", "Noble woman, goddess of love"),
    ("juniper", "Latin", "Young, evergreen"),
    ("magnolia", "Latin", "Magnol's flower"),
    ("sienna", "Italian", "Orange-red, from Siena"),
    ("maeve", "Irish", "Intoxicating, she who rules"),
    ("rosalie", "Latin", "Rose garden"),
    ("ophelia", "Greek", "Help, aid, serpentine"),
    ("phoenix", "Greek", "Reborn from ashes"),
    ("wren", "English", "Small bird"),
    ("dahlia", "Scandinavian", "Valley flower"),
    ("celeste", "Latin", "Heavenly"),
    ("clementine", "Latin", "Mild, merciful"),
    ("thea", "Greek", "Goddess, godly"),
    ("esme", "French", "Beloved, esteemed"),
    ("genevieve", "French", "White wave, tribe woman"),
    ("beatrice", "Latin", "She who brings happiness"),
    ("calliope", "Greek", "Beautiful voice"),
    ("florence", "Latin", "Flourishing, prosperous"),
    ("iris", "Greek", "Rainbow"),
    ("pearl", "Latin", "Precious gem"),
    ("theodora", "Greek", "Gift of God"),
    ("willa", "Germanic", "Resolute protector"),
    ("zelda", "Germanic", "Gray fighting maid"),
    ("imogen", "Celtic", "Maiden, girl"),
    ("seren", "Welsh", "Star"),
    ("poppy", "Latin", "Red flower"),
    ("elodie", "French", "Marsh flower"),
    # Additional popular names
    ("aidan", "Irish", "Little fire"),
    ("brayden", "Irish", "Descendant of Bradán"),
    ("cayden", "Arabic", "Companion, friend"),
    ("derek", "Germanic", "Ruler of the people"),
    ("eugene", "Greek", "Well-born, noble"),
    ("felix", "Latin", "Happy, fortunate"),
    ("gavin", "Welsh", "White hawk"),
    ("hayden", "English", "Hedged valley"),
    ("ivan", "Russian", "God is gracious"),
    ("jaden", "Hebrew", "God has heard"),
    ("kyle", "Gaelic", "Narrow strait"),
    ("lance", "French", "Land, territory"),
    ("marcus", "Latin", "Dedicated to Mars"),
    ("noel", "French", "Christmas"),
    ("oscar", "Irish", "Deer friend"),
    ("pierce", "English", "Rock, stone"),
    ("quincy", "French", "Fifth"),
    ("rex", "Latin", "King"),
    ("shane", "Irish", "God is gracious"),
    ("tristan", "Celtic", "Bold, tumult"),
    ("ulysses", "Latin", "Wrathful, wounded"),
    ("victor", "Latin", "Conqueror, winner"),
    ("wade", "English", "River crossing"),
    ("zane", "Hebrew", "God is gracious"),
    ("blake", "English", "Dark, fair"),
    ("cole", "English", "Charcoal, dark"),
    ("dean", "English", "Valley"),
    ("finn", "Irish", "Fair, white"),
    ("grant", "Scottish", "Great, large"),
    ("hugo", "Germanic", "Mind, intellect"),
    ("ivan", "Slavic", "God is gracious"),
    ("joel", "Hebrew", "The Lord is God"),
    ("knox", "Scottish", "Round hill"),
    ("leon", "Greek", "Lion"),
    ("milo", "Germanic", "Merciful, gracious"),
    ("otto", "Germanic", "Wealth, fortune"),
    ("reed", "English", "Red-haired"),
    ("seth", "Hebrew", "Appointed, placed"),
    ("troy", "Irish", "Foot soldier"),
    ("vaughn", "Welsh", "Small"),
    ("alan", "Celtic", "Handsome, cheerful"),
    ("bruce", "French", "Thick brush"),
    ("carl", "Germanic", "Free man"),
    ("dale", "English", "Valley"),
    ("earl", "English", "Nobleman, warrior"),
    ("floyd", "Welsh", "Gray-haired"),
    ("glenn", "Gaelic", "Valley, glen"),
    ("howard", "English", "High guardian"),
    ("irving", "Scottish", "Green water"),
    ("keith", "Scottish", "Forest, wood"),
    ("leon", "Greek", "Lion, brave"),
    ("marshall", "French", "Horse servant"),
    ("neil", "Gaelic", "Champion, cloud"),
    ("ralph", "Norse", "Wolf counsel"),
    ("russell", "French", "Red-haired"),
    ("stuart", "English", "Steward, guardian"),
    ("vernon", "French", "Alder tree grove"),
    ("warren", "Germanic", "Protector, loyal"),
    ("wayne", "English", "Wagon maker"),
    ("clyde", "Scottish", "Warm, from River Clyde"),
    ("darren", "Irish", "Great, oak tree"),
    ("ernest", "Germanic", "Serious, resolute"),
    ("gordon", "Scottish", "Large fortification"),
    ("herbert", "Germanic", "Bright army"),
    ("ivan", "Slavic", "God is gracious"),
    ("lloyd", "Welsh", "Gray-haired, sacred"),
    ("philip", "Greek", "Lover of horses"),
    ("roger", "Germanic", "Famous spear"),
    ("stanley", "English", "Stony meadow"),
    ("vincent", "Latin", "Conquering, prevailing"),
    ("wesley", "English", "Western meadow"),
    ("alma", "Latin", "Nourishing, kind"),
    ("bertha", "Germanic", "Bright, famous"),
    ("clara", "Latin", "Clear, bright"),
    ("edith", "English", "Prosperous in war"),
    ("flora", "Latin", "Flower"),
    ("gertrude", "Germanic", "Strong spear"),
    ("hilda", "Germanic", "Battle woman"),
    ("irene", "Greek", "Peace"),
    ("jane", "Hebrew", "God is gracious"),
    ("kate", "Greek", "Pure"),
    ("lena", "Greek", "Light, torch"),
    ("mabel", "Latin", "Lovable"),
    ("nina", "Spanish", "Little girl"),
    ("olive", "Latin", "Olive tree"),
    ("priscilla", "Latin", "Ancient, venerable"),
    ("rosa", "Latin", "Rose flower"),
    ("sylvia", "Latin", "Forest, woods"),
    ("thelma", "Greek", "Will, volition"),
    ("vera", "Russian", "Faith, truth"),
    ("wanda", "Slavic", "Wanderer"),
    ("ada", "Germanic", "Noble, happy"),
    ("bonnie", "Scottish", "Pretty, attractive"),
    ("daisy", "English", "Day's eye flower"),
    ("elsie", "Scottish", "God's promise"),
    ("fiona", "Gaelic", "Fair, white, beautiful"),
    ("greta", "Germanic", "Pearl"),
    ("ivy", "English", "Climbing vine plant"),
    ("joy", "English", "Happiness, delight"),
    ("lottie", "French", "Free woman"),
    ("millie", "Germanic", "Gentle strength"),
    ("opal", "Sanskrit", "Precious gem"),
    ("phoebe", "Greek", "Bright, shining"),
    ("rosemary", "Latin", "Dew of the sea"),
    ("tessa", "Greek", "Harvester"),
    ("una", "Irish", "One, unity"),
    ("wendy", "English", "Friend, blessed ring"),
    ("zara", "Arabic", "Princess, blooming flower"),
]


def main():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    updated = 0
    for name_lower, origin, meaning in NAME_DATA:
        result = c.execute(
            'UPDATE names SET origin = ?, meaning = ? WHERE slug = ? AND (origin IS NULL OR meaning IS NULL)',
            (origin, meaning, name_lower)
        )
        if result.rowcount > 0:
            updated += 1

    conn.commit()

    total = c.execute('SELECT COUNT(*) FROM names').fetchone()[0]
    with_meaning = c.execute('SELECT COUNT(*) FROM names WHERE meaning IS NOT NULL').fetchone()[0]
    with_origin = c.execute('SELECT COUNT(*) FROM names WHERE origin IS NOT NULL').fetchone()[0]

    print(f'Updated: {updated} names')
    print(f'Total names: {total}')
    print(f'With meaning: {with_meaning} ({with_meaning*100//total}%)')
    print(f'With origin: {with_origin} ({with_origin*100//total}%)')

    conn.close()


if __name__ == '__main__':
    main()
